require('config.options').setup()
require('config.keymaps').setup()
require('config.autocmds').setup()

require('plugins.colorscheme')
require('plugins.mini-pairs')
require('plugins.plenary')
require('plugins.telescope')
require('plugins.nvim-surround')
require('plugins.conform')
require('plugins.nvim-highlight-colors')
require('plugins.schemastore')
require('plugins.octo')
require('plugins.vim-dadbod')
require('plugins.mason')
require('plugins.nvim-lspconfig')
require('plugins.nvim-cmp')
require('plugins.luasnip')

require('core.lsp')
